plugins { id 'com.android.application' }

android {
    namespace 'com.jei.stockradar'
    compileSdk 35

    defaultConfig {
        applicationId 'com.jei.stockradar'
        minSdk 26
        targetSdk 35
        versionCode 21
        versionName '3.0.1'
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        debug { minifyEnabled false }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}


dependencies {
    implementation 'androidx.work:work-runtime:2.9.1'
}
